BasicApp/Models/Bootcamp.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BasicApp.Models
{
    public class Bootcamp
    {
        public int Id { get; set; }
        public string? Title { get; set; }
        public string? Description { get; set; }
        public string? Instructor { get; set; }
        public string? Image { get; set; }
        public bool isActive {get;set;}
        public bool isHome {get;set;}
        public string[]? tag {get;set;}
    }
}

BasicApp/Models/ErrorViewModel.cs
namespace BasicApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

BasicApp/Models/Repository.cs
namespace BasicApp.Models
{
    public class Repository{

        private static readonly List<Bootcamp> _bootcamp = new();

        static Repository(){
            _bootcamp = new List<Bootcamp>(){
                new() {Id = 1, Title = "Backend Bootcamp",Description="Güzel eğitim.", Instructor = "Ahmet Kaya", Image = "1.png", tag = new string[] {"web geliştirme", "asp.net"}, isActive = false, isHome = false},
                new() {Id = 2, Title = "Froundend Bootcamp",Description="Güzel eğitim.", Instructor = "Barış Uygun", Image = "2.png", tag = new string[] {"web geliştirme", "html" ,"Css"}, isActive = true, isHome = false},
                new() {Id = 3, Title = "Unity Bootcamp",Description="Güzel eğitim.", Instructor = "Özge Dirik", Image = "3.png", tag = new string[] {"oyun geliştirme", "unity"}, isActive = true, isHome = true},
            };
        }

        public static List<Bootcamp> Bootcamps{get{return _bootcamp;}}

        public static Bootcamp? GetById(int id){
            return _bootcamp.FirstOrDefault(b=>b.Id == id);
        }

    }
}

BasicApp/Controllers/BootcampController.cs
using BasicApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace BasicApp.Controllers
{
    public class BootcampController:Controller
    {
        public IActionResult Index(){
            return View(Repository.Bootcamps);
        }    
        public IActionResult Details(int id){
            
            var bootcamp = Repository.GetById(id);
            return View(bootcamp);
        }  

        public IActionResult List(){
            return View(Repository.Bootcamps);
        }
    }
}

BasicApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using BasicApp.Models;

namespace BasicApp.Controllers;

public class HomeController : Controller
{

    public IActionResult Index()
    {
        return View();
    }
    
}

BasicApp/Views/Bootcamp/Details.cshtml
@model Bootcamp

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h1 class="mt-1">@Model.Title</h1><hr>
            <img src="~/img/@Model.Image" alt="" class="img-fluid mb-5">
            <p class="card-title">@Model.Description</p>
            <div>
                @if(Model.tag != null){
                @foreach(var tag in Model.tag){
                    <span class="badge bg-warning">@tag</span>
                }
                }
            </div>
            <p class="lead">@Model.Instructor</p>

        </div>
    </div>
</div>

BasicApp/Views/Bootcamp/List.cshtml
@model List<Bootcamp>

    <h2>Bootcamp Listesi</h2>
    <hr>
    @foreach(var bootcamp in Model)
    {
        @if(bootcamp.isActive){
        @await Html.PartialAsync("_List",bootcamp);
        }
    }

BasicApp/Views/Bootcamp/_List.cshtml
@model Bootcamp
<div class="card mb-3" id=".Id">
            <img src="~/img/@Model.Image" alt="" class="card-img-top" style="height: 300px; object-fit: cover">
            <div class="card-body">
                <a asp-controller="Bootcamp" asp-action="Details" asp-route-id="@Model.Id">
                    <h1 class="card-title">@Model.Title</h1>
                </a>
            <p class="card-text">@Model.Description</p>
            <p class="card-text">@Model.Instructor</p>
            </div>
        </div>

BasicApp/Views/Bootcamp/index.cshtml
@model List<Bootcamp>
@await Html.PartialAsync("_Slider")

<div class="row">
@foreach(var bootcamp in Model){
  @if(bootcamp.isActive && bootcamp.isHome){
    <div class="col-3">
<div class="card" style="width: 18rem;">
  <img src="~/img/@bootcamp.Image" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">@bootcamp.Title</h5>
    <p class="card-text">@bootcamp.Description</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">@bootcamp.Instructor</li>
  </ul>
  <div class="card-body">
    <a asp-controller="Bootcamp" asp-action="Details" asp-route-id="@bootcamp.Id" class="btn btn-primary">Detay</a>
  </div>
</div>
</div>
  }
}
</div>

BasicApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BasicApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BasicApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @await Html.PartialAsync("_Navbar")
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BasicApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BasicApp/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BasicApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 container">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bootcamp" asp-action="Index">Bootcamp</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bootcamp" asp-action="List">Bootcamps</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

BasicApp/Views/Shared/_Slider.cshtml
<div id="carouselExampleSlidesOnly" class="carousel slide mb-4" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="~/img/1.png" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="~/img/2.png" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="~/img/3.png" class="d-block w-100" alt="...">
    </div>
  </div>
</div>