efcoreApp/Controllers/BootcampKayitController.cs
using efcoreApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace efcoreApp.Controllers
{
    public class BootcampKayitController:Controller
    {
        private readonly DataContext _context;
        public BootcampKayitController(DataContext context)
        {   
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var kursKayitlari = await _context
                                .Kayitlar
                                .Include(x=>x.Ogrenci)
                                .Include(x=>x.Kurs)
                                .ToListAsync();
            return View(kursKayitlari);
        } 

        public async Task<IActionResult> Create()
        {
            ViewBag.Ogrenciler = new SelectList(await _context.Ogrenciler.ToListAsync(), "OgrenciId","AdSoyad");
            ViewBag.Kurslar = new SelectList(await _context.Bootcamps.ToListAsync(), "KursId","Baslik");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]        
        public async Task<IActionResult> Create(BootcampKayit model)
        {
            model.KayitTarihi = DateTime.Now;
            _context.Kayitlar.Add(model);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }


    }
}

efcoreApp/Views/BootcampKayit/Create.cshtml
@model BootcampKayit

<h2>Kurs Kayıt Ekleme</h2>
<hr>
<form asp-controller="BootcampKayit" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="OgrenciId" class="form-label">Öğrenci</label>
        <select asp-for="OgrenciId" asp-items="ViewBag.Ogrenciler" class="form-control">
            <option value="">Seçiniz</option>
        </select>
    </div>
    <div class="mb-3">
        <label asp-for="KursId" class="form-label">Kurs</label>
        <select asp-for="KursId" asp-items="ViewBag.Kurslar" class="form-control">
            <option value="">Seçiniz</option>
        </select>
    </div>

    <button type="submit" class="btn btn-secondary">Kaydet</button>

</form>

efcoreApp/Views/BootcampKayit/Index.cshtml
@model IEnumerable<BootcampKayit>

<h2>Öğrenci Listesi</h2>
<a href="/BootcampKayit/Create" class="btn btn-primary">Kurs Ekle</a>
<hr>
<table class="table table-bordered">
    <thead>
        <tr>
            <th style="width: 150px;">@Html.DisplayNameFor(m => m.KayitId)</th>
            <th>@Html.DisplayNameFor(m => m.Ogrenci.OgrenciAd)</th>
            <th>@Html.DisplayNameFor(m => m.Kurs.Baslik)</th>
            <th style="width: 150px;"></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.KayitId)</td>
                <td>@Html.DisplayFor(modelItem => item.Ogrenci.OgrenciAd)</td>
                <td>@Html.DisplayFor(modelItem => item.Kurs.Baslik)</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.OgrenciId" class="btn btn-sm btn-primary">Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.OgrenciId" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>